#%RAML 1.0
title: API Key Protected API
version: 1.0
baseUri: https://api.example.com

securitySchemes:
  apiKey:
    type: Pass Through
    description: API Key in header
    describedBy:
      headers:
        X-API-Key:
          type: string
          required: true

securedBy: [apiKey]

/resources:
  get:
    description: Get resources
    responses:
      200:
        description: Resources retrieved
  
  /public:
    get:
      description: Public endpoint
      securedBy: [null]
      responses:
        200:
          description: Public data
          